# GoReleaser configuration for kira CLI
version: 2

project_name: kira

builds:
  - id: kira
    main: ./cmd/kira/main.go
    binary: kira
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7" # for arm64 compatibility
    ldflags:
      - -X 'kira/internal/commands.Version={{.Tag}}'
      - -X 'kira/internal/commands.Commit={{.ShortCommit}}'
      - -X 'kira/internal/commands.BuildDate={{.Date}}'
      - -X 'kira/internal/commands.Dirty=clean'
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
      - kira.yml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: taskforce-labs
    name: kira
  mode: replace
  header: |
    ## What's Changed
  footer: |
    **Full Changelog**: https://github.com/taskforce-labs/kira/compare/{{ .PreviousTag }}...{{ .Tag }}

homebrew_casks:
  - name: kira
    description: "Git-based, plaintext productivity tool designed with both clankers (LLMs) and meatbags (people) in mind"
    homepage: "https://github.com/taskforce-labs/kira"
    license: "MIT"
    binaries:
      - kira
    repository:
      owner: taskforce-labs
      name: homebrew-kira
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kira"]
          end

scoops:
  - name: kira
    description: "Git-based, plaintext productivity tool designed with both clankers (LLMs) and meatbags (people) in mind"
    homepage: "https://github.com/taskforce-labs/kira"
    license: "MIT"
    repository:
      owner: taskforce-labs
      name: scoop-bucket
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    persist:
      - data

